spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234!
    url: jdbc:mysql://localhost:3302/mokaform_user
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

server:
  port: 8081